{
 "title": "Simple energy aggregations dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": "Gradiška,Banja Luka,Prijedor,Bihać,Doboj,Tuzla,Bijeljina,Sarajevo,Mostar,Trebinje,Zvornik,Zenica"
   }
  ]
 },
 "panels": [
  {
   "title": "Total consumption in $city",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Sarajevo\")\r\n\r\nfrom(bucket: \"simple-energy-aggregator\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"city-aggregation\" and r[\"cityName\"] == \"$city\" and r[\"_field\"] == \"aggregatedActiveDelta\")\r\n"
    }
   ]
  },
  {
   "title": "Total consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Sarajevo\")\r\n\r\nfrom(bucket: \"simple-energy-aggregator\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"country-aggregation\")\r\n"
    }
   ]
  },
  {
   "title": "Total hourly consumption in $city",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Sarajevo\")\r\n\r\nfrom(bucket: \"simple-energy-aggregator\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"city-aggregation\" and r[\"cityName\"] == \"$city\" and r[\"_field\"] == \"aggregatedActiveDelta\")\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> timeShift(duration: -1h)"
    }
   ]
  },
  {
   "title": "Total hourly consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Sarajevo\")\r\n\r\nfrom(bucket: \"simple-energy-aggregator\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"country-aggregation\")\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> timeShift(duration: -1h)"
    }
   ]
  },
  {
   "title": "Geomap",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Sarajevo\")\r\n\r\nfrom(bucket: \"simple-energy-aggregator\")\r\n  |> range(start: -40s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"city-aggregation\")\r\n  |> last()\r\n  |> pivot(\r\n    rowKey:[\"_time\"],\r\n    columnKey: [\"_field\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> group()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\r\n"
    }
   ]
  }
 ]
}