version: "3"

services:
  influxdb:
    image: influxdb
    volumes:
      - "influxdb_data:/var/lib/influxdb2"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=sigurnost
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=simple-energy-aggregator
      - DOCKER_INFLUXDB_INIT_RETENTION=24h
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    deploy:
        resources:
            limits:
                memory: 500M
volumes:
    influxdb_data:
        driver: local

# Web UI can be accessed at localhost:8086/orgs/my-org-name/dashboards