version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=vQStvk5ileb3Mhw0
      - AWS_SECRET_KEY=4rhALdLpPa8IBXxDehI69Ki3613krErB
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
        - type: bind
          read_only: true
          source: D:\Diplomski rad\Prakticni dio\Simple energy aggregator\target\
          target: /jobs/
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=vQStvk5ileb3Mhw0
      - AWS_SECRET_KEY=4rhALdLpPa8IBXxDehI69Ki3613krErB
    volumes:
        - type: bind
          read_only: true
          source: D:\Diplomski rad\Prakticni dio\Simple energy aggregator\target\
          target: /jobs/