version: '3'

services:
  spark:
    image: custom-spark-image
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=MkHLU0kWvwdkoVKz
      - AWS_SECRET_KEY=9e6wo9iw2CfpSNO3BeQeAHAfsUYu2aFC
      - SPARK_SQL_SHUFFLE_PARTITIONS=3
      - HOURLY_AGGREGATOR_SPARK_SQL_SHUFFLE_PARTITIONS=4
      - HOURLY_AGGREGATOR_OUTPUT_PATH=simple-energy-aggregator/energy-data/
      - MINIO_ENDPOINT=minio:9000
      - KAFKA_BOOTSTRAP_SERVERS=desktop-kafka-1:9092
    ports:
      - '8080:8080'
      - '7077:7077'
    deploy:
        resources:
            limits:
                memory: 1G
    #volumes:
    #    - type: bind
    #      read_only: true
    #      source: D:\Diplomski rad\Prakticni dio\Simple energy aggregator\target\simple-energy-aggregator-1.0-SNAPSHOT.jar
    #      target: /opt/bitnami/spark/jars/simple-energy-aggregator-1.0-SNAPSHOT.jar
  spark-worker:
    image: custom-spark-image
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://desktop-spark-1:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - AWS_ACCESS_KEY=MkHLU0kWvwdkoVKz
      - AWS_SECRET_KEY=9e6wo9iw2CfpSNO3BeQeAHAfsUYu2aFC
      - SPARK_SQL_SHUFFLE_PARTITIONS=3
      - HOURLY_AGGREGATOR_SPARK_SQL_SHUFFLE_PARTITIONS=4
      - HOURLY_AGGREGATOR_OUTPUT_PATH=simple-energy-aggregator/energy-data/
      - KAFKA_BOOTSTRAP_SERVERS=desktop-kafka-1:9092
    deploy:
        resources:
            limits:
                memory: 1G
        replicas: 2
    #volumes:
    #    - type: bind
    #      read_only: true
    #      source: D:\Diplomski rad\Prakticni dio\Simple energy aggregator\target\simple-energy-aggregator-1.0-SNAPSHOT.jar
    #      target: /opt/bitnami/spark/jars/simple-energy-aggregator-1.0-SNAPSHOT.jar